import FastaExport from '$lib/FastaExport.svelte';
import '../app.css';

export default {
	title: 'Export/FastaExport',
	component: FastaExport,
	argTypes: {
		alignmentFile: { control: 'object' },
		showExport: { control: 'boolean' }
	},
	parameters: {
		docs: {
			description: {
				component:
					'Specialized export component for sequence data. Supports FASTA and NEXUS export formats with line wrapping option. Parses alignment files directly to extract sequences.'
			}
		}
	}
};

// Helper to create a mock File object
function createMockFile(content, filename, type = 'text/plain') {
	const blob = new Blob([content], { type });
	return new File([blob], filename, { type });
}

// Sample FASTA content
const sampleFastaContent = `>HIV-1_A1_U455
ATGGCAGATGATTTGTTAGTAGATGGAGGGGTTAACGAAAGCCCAATAAATTTGGGAAAGCTGGGTTATAATGATAAAGTGTTAATAAACGTTTGTGATTCAAAGCTTAATTGCTTAGAGGATATAAATTATAAGGCATTGAAAGAGGCAATAAAAAAATTAGGAGAACTTTTCTATAACATGGCAGTT
>HIV-1_B_HXB2
ATGGCAGATGATTTGTTAGTAGATGGAGGGGTTAACGAAAGCCCAATAAATTTGGGAAAGCTGGGTTATAATGATAAAGTGTTAATAAACGTTTGTGATTCAAAGCTTAATTGCTTAGAGGATATAAATTATAAGGCATTGAAAGAGGCAATAAAAAAATTAGGAGAACTTTTCTATAACATGGCAGTT
>HIV-1_C_ETH222
ATGGCAGATGATTTGTTAGTAGATGGAGGGGTTAACGAAAGCCCAATAAATTTGGGAAAGCTGGGTTATAATGATAAAGTGTTAATAAACGTTTGTGATTCAAAGCTTAATTGCTTAGAGGATATAAATTATAAGGCATTGAAAGAGGCAATAAAAAAATTAGGAGAACTTTTCTATAACATGGCAGTT
>HIV-1_D_84ZR085
ATGGCAGATGATTTGTTAGTAGATGGAGGGGTTAACGAAAGCCCAATAAATTTGGGAAAGCTGGGTTATAATGATAAAGTGTTAATAAACGTTTGTGATTCAAAGCTTAATTGCTTAGAGGATATAAATTATAAGGCATTGAAAGAGGCAATAAAAAAATTAGGAGAACTTTTCTATAACATGGCAGTT
>HIV-1_F1_VI850
ATGGCAGATGATTTGTTAGTAGATGGAGGGGTTAACGAAAGCCCAATAAATTTGGGAAAGCTGGGTTATAATGATAAAGTGTTAATAAACGTTTGTGATTCAAAGCTTAATTGCTTAGAGGATATAAATTATAAGGCATTGAAAGAGGCAATAAAAAAATTAGGAGAACTTTTCTATAACATGGCAGTT`;

const sampleFastaWithGaps = `>Sequence_1
ATGCGA---TCGATCGATCGATCGATCGATCG---ATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCG---ATCGATCGATCG
>Sequence_2
ATGCGATCG---ATCGATCGATCGATCGATCGATCG---ATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCG---ATCGATCG
>Sequence_3
ATGCGATCGATCG---ATCGATCGATCGATCGATCGATCG---ATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCG---ATCG
>Sequence_4
ATGCGATCGATCGATCG---ATCGATCGATCGATCGATCGATCG---ATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCGATCG---`;

const sampleNexusContent = `#NEXUS

BEGIN DATA;
  DIMENSIONS NTAX=5 NCHAR=187;
  FORMAT DATATYPE=DNA GAP=- MISSING=?;
  MATRIX
    HUMAN    ATGGCAGATGATTTGTTAGTAGATGGAGGGGTTAACGAAAGCCCAATAAATTTGGGAAAGCTGGGTTATAATGATAAAGTGTTAATAAACGTTTGTGATTCAAAGCTTAATTGCTTAGAGGATATAAATTATAAGGCATTGAAAGAGGCAATAAAAAAATTAGGAGAACTTTTCTATAACATGGCAGTT
    CHIMP    ATGGCAGATGATTTGTTAGTAGATGGAGGGGTTAACGAAAGCCCAATAAATTTGGGAAAGCTGGGTTATAATGATAAAGTGTTAATAAACGTTTGTGATTCAAAGCTTAATTGCTTAGAGGATATAAATTATAAGGCATTGAAAGAGGCAATAAAAAAATTAGGAGAACTTTTCTATAACATGGCAGTT
    GORILLA  ATGGCAGATGATTTGTTAGTAGATGGAGGGGTTAACGAAAGCCCAATAAATTTGGGAAAGCTGGGTTATAATGATAAAGTGTTAATAAACGTTTGTGATTCAAAGCTTAATTGCTTAGAGGATATAAATTATAAGGCATTGAAAGAGGCAATAAAAAAATTAGGAGAACTTTTCTATAACATGGCAGTT
    MOUSE    ATGGCAGATGATTTGTTAGTAGATGGAGGGGTTAACGAAAGCCCAATAAATTTGGGAAAGCTGGGTTATAATGATAAAGTGTTAATAAACGTTTGTGATTCAAAGCTTAATTGCTTAGAGGATATAAATTATAAGGCATTGAAAGAGGCAATAAAAAAATTAGGAGAACTTTTCTATAACATGGCAGTT
    RAT      ATGGCAGATGATTTGTTAGTAGATGGAGGGGTTAACGAAAGCCCAATAAATTTGGGAAAGCTGGGTTATAATGATAAAGTGTTAATAAACGTTTGTGATTCAAAGCTTAATTGCTTAGAGGATATAAATTATAAGGCATTGAAAGAGGCAATAAAAAAATTAGGAGAACTTTTCTATAACATGGCAGTT
  ;
END;`;

const Template = (args) => ({
	Component: FastaExport,
	props: args
});

export const Default = Template.bind({});
Default.args = {
	alignmentFile: createMockFile(sampleFastaContent, 'hiv_sequences.fasta'),
	showExport: true
};
Default.parameters = {
	docs: {
		description: {
			story: 'Default export panel showing format selection (FASTA, NEXUS) and line wrap option.'
		}
	}
};

export const WithGappedSequences = Template.bind({});
WithGappedSequences.args = {
	alignmentFile: createMockFile(sampleFastaWithGaps, 'gapped_alignment.fasta'),
	showExport: true
};
WithGappedSequences.parameters = {
	docs: {
		description: {
			story: 'Export panel with sequences containing gap characters (---). Gaps are preserved in both FASTA and NEXUS exports.'
		}
	}
};

export const NexusInput = Template.bind({});
NexusInput.args = {
	alignmentFile: createMockFile(sampleNexusContent, 'alignment.nex'),
	showExport: true
};
NexusInput.parameters = {
	docs: {
		description: {
			story: 'Export panel with a NEXUS format input file. The component parses NEXUS and can export to either format.'
		}
	}
};

export const Hidden = Template.bind({});
Hidden.args = {
	alignmentFile: createMockFile(sampleFastaContent, 'sequences.fasta'),
	showExport: false
};
Hidden.parameters = {
	docs: {
		description: {
			story: 'Export panel with showExport set to false - component is not rendered.'
		}
	}
};

export const NoFile = Template.bind({});
NoFile.args = {
	alignmentFile: null,
	showExport: true
};
NoFile.parameters = {
	docs: {
		description: {
			story: 'Export panel when no alignment file is available. Component will not render.'
		}
	}
};
